import Link from "next/link";

export default function Landing(){
 return <main className="landing">
  <nav className="landingNav"><Link href="/" className="brand"><span className="brandMark">L</span>Launchic</Link><div className="navLinks"><Link href="#how">How it works</Link><Link href="#who">Who it's for</Link><Link href="/login">Log in</Link><Link href="/signup" className="button primary">Start Building</Link></div></nav>
  <section className="landingHero"><div className="heroCopy"><div className="eyebrow">THE AI OPERATING SYSTEM FOR STARTING & GROWING</div><h1>Find What to Build.<br/>Know What to Do Next.</h1><p>Launchic helps you discover business opportunities, validate ideas, launch faster, and grow what works.</p><div className="heroActions"><Link href="/signup" className="button primary">Start Building</Link><Link href="#how" className="button secondary">See How It Works</Link></div></div><div className="productPreview"><div className="previewTop"><strong>Launchic</strong><span>Overview</span></div><div className="previewBody"><div className="previewLabel">NEXT BEST ACTION</div><h3>Interview five potential customers.</h3><p>Validate whether your strongest opportunity solves a painful enough problem before you build.</p><div className="previewRow"><span>Priority <b>High</b></span><span>Stage <b>Validation</b></span></div><button>Add to Launchpad</button></div></div></section>
  <section className="problem"><div className="eyebrow">THE PROBLEM</div><h2>Too many ideas. Too much data. No clear next move.</h2><p>People struggle to know what to build, which idea is worth pursuing, what customers actually want, and where their attention should go. Launchic turns context into decisions.</p></section>
  <section id="how" className="how"><div className="eyebrow">HOW IT WORKS</div><div className="steps">{["SCOUT|Discover ideas and opportunities.","UNDERSTAND|Build your Business Brain.","VALIDATE|Test whether an opportunity is worth pursuing.","LAUNCH|Turn decisions into actions.","GROW|Measure results and improve."].map((x,i)=>{const [a,b]=x.split("|");return <div className="step" key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>})}</div></section>
  <section id="who" className="paths"><div><div className="eyebrow">STARTING FROM ZERO</div><h2>No idea required.</h2><p>Explore your interests, skills, and problems you care about. Scout helps turn them into opportunities worth investigating.</p><b>No Idea → Ideas → Validation → Business</b></div><div><div className="eyebrow">ALREADY BUILDING</div><h2>Grow with context.</h2><p>Connect your business context and let Launchic surface the opportunities, actions, and signals that deserve attention.</p><b>Business → Opportunities → Actions → Growth</b></div></section>
  <section className="finalCta"><h2>Your next move starts here.</h2><Link href="/signup" className="button primary">Start Building</Link></section>
 </main>
}